export enum EOrderActivityType {
  CREATED = 'CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  UPDATED = 'UPDATED',
  NOTE_ADDED = 'NOTE_ADDED',
  ADVANCE_PAYMENT = 'ADVANCE_PAYMENT',
  ATTACHMENT_ADDED = 'ATTACHMENT_ADDED',
  ATTACHMENT_REMOVED = 'ATTACHMENT_REMOVED',
  CUSTOMER_NOTIFIED = 'CUSTOMER_NOTIFIED',
  CANCELLED = 'CANCELLED',
}
